name: Periodic Health Check

on:
  push:
  # schedule:
  #   - cron: '0 12 * * *'  # один раз в день в 12:00 UTC

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-9sj5.onrender.com/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
